/**
 * Format the daily self-organization artifact (markdown).
 */

/**
 * @param {{
 *   date: string,
 *   personaSource: string,
 *   card: object,
 *   trail: Array<object>,
 *   projects: Array<object>,
 *   actions: Array<object>,
 *   schedule: Array<object>,
 *   balance: number,
 *   publicActions: Array<object>,
 *   privateActions: Array<object>,
 *   hitlActions: Array<object>,
 *   injections: Array<object>,
 * }} data
 */
export function formatDailyPlan(data) {
  const lines = [];
  lines.push(`# Daily Swarm Plan — ${data.date}`);
  lines.push('');
  lines.push(`> Generated by ensembly swarm control loop. Persona source: \`${data.personaSource}\`.`);
  lines.push('');
  lines.push('## Loop control');
  lines.push('');
  lines.push(`- **goal:** ${data.card.goal}`);
  lines.push(`- **phase:** ${data.card.phase}`);
  lines.push(`- **status trail:** ${(data.trail || []).map((t) => t.phase).join(' → ')}`);
  lines.push(
    `- **budgets:** max_loop_iters=${data.card.budgets.max_loop_iters}, max_repair_rounds=${data.card.budgets.max_repair_rounds}`,
  );
  lines.push(`- **pause_reason:** ${data.card.pause_reason || 'none'}`);
  lines.push('');

  lines.push('## Projects (inception / prioritization)');
  lines.push('');
  lines.push('| Rank | ID | Title | Area | Quadrant | Score | Visibility |');
  lines.push('|------|----|-------|------|----------|-------|------------|');
  (data.projects || []).forEach((p, i) => {
    const vis = p.classification?.visibility || (p.public ? 'public' : 'private');
    lines.push(
      `| ${i + 1} | ${p.id} | ${esc(p.title)} | ${p.area} | ${p.quadrant || '—'} | ${fmtScore(p.score)} | ${vis} |`,
    );
  });
  lines.push('');

  lines.push('## Actions (curated)');
  lines.push('');
  if (!(data.actions || []).length) {
    lines.push('_No actions — verify inputs._');
  } else {
    for (const a of data.actions) {
      const vis = a.classification?.visibility || 'private';
      const hitl = a.classification?.hitl ? ' **[HITL]**' : '';
      const src = a.source ? ` _(source: ${a.source})_` : '';
      lines.push(
        `- **[${vis}]** ${a.title || a.id} — ${a.area} · ${a.quadrant || '—'} · score ${fmtScore(a.score)}${hitl}${src}`,
      );
    }
  }
  lines.push('');

  lines.push('## Schedule & balance');
  lines.push('');
  lines.push(`- **balance score:** ${data.balance} (1.0 = strong coverage of non-negotiables + diversity)`);
  if ((data.injections || []).length) {
    lines.push(
      `- **balance injections:** ${data.injections.map((i) => i.id).join(', ')}`,
    );
  }
  lines.push('');
  lines.push('| Start | End | Block | Assigned | Areas |');
  lines.push('|-------|-----|-------|----------|-------|');
  for (const s of data.schedule || []) {
    const assigned = s.assigned ? `${s.assigned.title} (${s.assigned.area})` : '—';
    const nn = s.non_negotiable ? ' 🔒' : '';
    lines.push(
      `| ${s.start} | ${s.end} | ${esc(s.label)}${nn} | ${esc(assigned)} | ${(s.areas || []).join(', ')} |`,
    );
  }
  lines.push('');

  lines.push('## Privacy split');
  lines.push('');
  lines.push(`- **public / pushable actions:** ${(data.publicActions || []).length}`);
  lines.push(`- **private / local-only actions:** ${(data.privateActions || []).length}`);
  lines.push(`- **HITL-gated:** ${(data.hitlActions || []).length}`);
  lines.push('');
  if ((data.publicActions || []).length) {
    lines.push('### Public (shareable)');
    for (const a of data.publicActions) {
      lines.push(`- ${a.title || a.id}`);
    }
    lines.push('');
  }
  if ((data.privateActions || []).length) {
    lines.push('### Private (local only — do not push)');
    for (const a of data.privateActions) {
      lines.push(`- ${a.title || a.id} — ${a.classification?.reason || 'private'}`);
    }
    lines.push('');
  }

  lines.push('## HITL pause points');
  lines.push('');
  if ((data.hitlActions || []).length === 0) {
    lines.push('- None for auto-executable local plan assembly. External mutates still require human confirmation by policy.');
  } else {
    for (const a of data.hitlActions) {
      lines.push(`- **PAUSE:** ${a.title || a.id} — ${a.classification?.reason || 'high stakes'}`);
    }
  }
  lines.push('');
  lines.push('---');
  lines.push('_ensembly swarm · looper-bounded day cycle · privacy-default-deny_');
  lines.push('');
  return lines.join('\n');
}

function esc(s) {
  return String(s || '').replace(/\|/g, '\\|');
}

function fmtScore(n) {
  if (n === undefined || n === null) return '—';
  return typeof n === 'number' ? n.toFixed(2) : String(n);
}
